#!/bin/bash
sudo apt-get update
sudo apt-get install git vim htop tree 

# git extras
(cd /tmp && git clone --depth 1 https://github.com/tj/git-extras.git && cd git-extras && sudo make install)

./setupdotfiles
